### PR TITLE
Check python-config for --embed flag (python 3.8 compatibility)

### PR DESCRIPTION
**Pull request by ellert**
Addresses Issue #87. See that issue for details.

### CODE REVIEW

**Comment by stratakis** [comment]
Tested the PR on the Fedora package and it builds fine with Python 3.7 as well as Python 3.8.

Also a simpler fix (but the same functionally nonetheless)  may be to just replace
`PYTHON_LIBS="$LIBS $($PYTHON_CONFIG --libs)"`

with

`PYTHON_LIBS="$LIBS $($PYTHON_CONFIG --libs --embed)" || PYTHON_LIBS="$LIBS $($PYTHON_CONFIG --libs)"`

**Comment by matyasselmeci** [comment]
Are the LDFLAGS no longer needed, or not used anywhere?

**Comment by stratakis** [comment]
With 3.7 on Fedora:
$ python3-config --ldflags
-L/usr/lib64 -lpython3.7m -lcrypt -lpthread -ldl  -lutil -lm  -Xlinker -export-dynamic
$ python3-config --libs
-lpython3.7m -lcrypt -lpthread -ldl  -lutil -lm

With 3.8 on Fedora:
$ python3-config --ldflags
-L/usr/lib64  -lcrypt -lpthread -ldl  -lutil -lm -lm
$ python3-config --libs
-lcrypt -lpthread -ldl  -lutil -lm -lm

**Comment by ellert** [comment]
> Are the LDFLAGS no longer needed, or not used anywhere?

We do not need both --libs and --ldflags. (As we do not need both --includes and --cflags.)

**Pull request merged**
