### PR TITLE
Enable additional CI build targets

### PR DESCRIPTION
**Pull request by fscheiner**
* CentOS Stream 8 and 9
* RockyLinux 8

### CODE REVIEW

**Comment by fscheiner** [comment]
New target OSes are limited to GHA and the x86_64 arch. Depending on availability in the future this can be extended to the ppc64le (and maybe also to the arm64, but not used yet!) arch(es) used with Travis CI.

**Comment by fscheiner** [comment]
[The Travis-CI build for this PR](https://app.travis-ci.com/github/gridcf/gct/jobs/567650081) failed because it was automatically cancelled after a runtime of more than 50 minutes. But [the corresponding Travis-CI build in my fork for the pushed branch that is the base for this PR](https://app.travis-ci.com/github/fscheiner/gct/builds/249633795) succeeded.

Hence the checks for this PR can be considered successful.

**Review by msalle — APPROVED** [review]
Looks good to me

**Review by ellert — APPROVED** [review]
I requested a re-run of the failed test, and it succeeded in 49m 11s  (Which is less than 50 minutes, but not by much.)

**Comment by fscheiner** [comment]
@ellert, @msalle:
> I requested a re-run of the failed test, and it succeeded in 49m 11s (Which is less than 50 minutes, but not by much.)

Indeed it's a very tight margin to failure here. I'll look into further splitting up the build jobs for Travis CI to see if this makes a difference.

**Pull request merged**
