### PR TITLE
Fix exit code of status command in the gridftp service

### PR DESCRIPTION
**Pull request by brianhlin**
Addresses #47

### CODE REVIEW

**Comment by matyasselmeci** [comment]
This code works because $rc in that function is actually global so it gets propagated to the caller, but you need to read it closely to realize that. I suggest changing the case statement like in #47.

**Comment by fscheiner** [comment]
Just had a quick look: I think the problem described in #47 is due to missing LSB functions at the OP's machine, so instead of `status_lsb` only `status` is called which does not set `$rc` but just returns a value, but the `exit $rc` at the end of the "main" `case` clause doesn't anticipate this.

As all functions return a value (either the value of "$rc" or just a value), the easiest solution might be to change the last `exit` call to `exit $?` (which will exit with the return or exit value of the last called function or tool) or just `exit` (which will act the same way).

What do you think about that?

**Comment by brianhlin** [comment]
Personally, I think it's nice to explicitly state `exit $exit_code` but I'm also fine with `exit $?` at the end, too.

**Comment by brianhlin** [comment]
Note that the commit (https://github.com/gridcf/gct/commit/cef7e1e3a2bdc93631cf2c25a947cfd07fc76b1a) fixes it depending on the global `rc` variable, which we decided against in this PR. However, I think for such a minor fix it doesn't warrant diverging away from upstream

**Pull request closed without merging**
