### PR TITLE
Merge changes from globus/globus-toolkit repo made since our fork

### PR DESCRIPTION
**Pull request by matyasselmeci**

### CODE REVIEW

**Comment by bbockelm** [comment]
I see a few version numbers have been bumped upstream - is there anything we need to consider here?

**Comment by msalle** [comment]
Wouldn't it make sense, at least for the time being, to track directly the globus-toolkit as an upstream branch?

**Comment by matyasselmeci** [comment]
I'd be fine with that. It would give us a use for `globus_6_branch`.

**Comment by matyasselmeci** [comment]
OK, merging. For `osg-bot`, I guess I'd like something that pulls their globus_6_branch into ours, then does a force push. And in the future, we'll make pull requests into master from our globus_6_branch.

**Pull request merged**
