### PR TITLE
Compatibility with autoconf 2.72

### PR DESCRIPTION
**Pull request by ellert**
Fix for https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1086241

### CODE REVIEW

**Comment by fscheiner** [comment]
Looks good to me. Thanks for fixing, @ellert.

I only wonder what changed outside of the GCT that the old code now made a problem.

**Comment by ellert** [comment]
> I only wonder what changed outside of the GCT that the old code now made a problem.

I had a closer look, and this is due to changes in autoconf 2.72.
I have therefore reworked the pull request. Please review again.

**Review by fscheiner — APPROVED** [review]
Assuming that (i.e. `[...]file_offset_bits`) is no longer relevant for autoconf 2.72, I'd say let's do this.

**Comment by fscheiner** [comment]
Also the failing check should be fixed by #233.

**Pull request merged**
